### ISSUE TITLE
Unstructured VTK grid support

### ISSUE THREAD

**Issue by ozgurozansen** [elrnv/gltfgen#3]
Excellent tool here. I appreciate your remarkable job. 
Yet, it would be much more convenient if it supported unstructured VTK grid files such as .vtu, .pvtu, .vtp. Do you have any future plans for integrating them into your tool?

**Comment by elrnv** [comment]
Thank you for submitting the issue!
The short answer is yes. The long answer has two parts.
1. There are plans in supporting the xml-based formats in https://github.com/elrnv/vtkio/issues/4 (these are the `.vtu` `.pvtu` `.vtp` types).
2. I'm sure you already know this, but for others I will mention: For generating gltf files, this functionality is mostly there since the legacy `.vtk` format already supports unstructured grids, so one could already use these by converting from say `.vtu` to `.vtk` if possible.

Are there some gltf specific output capabilities you are looking for? Otherwise this is an issue for [`vtkio`](https://github.com/elrnv/vtkio).

**Comment by elrnv** [comment]
Preliminary support for .vtu, .pvtu, .vtp and .pvtp files is added in v0.5.0.
